### PR TITLE
Split library

### PR DESCRIPTION
**Pull request by JPMoresmau**
To be able to reuse the conversion from the GHC ASTs to Values, I've moved the main code into a library, that the executable then uses. I've cut the library into several functions, so that it can be used if you're already in the GHC Monad, and also you can get trees from whatever targets are in your session. I have validated that by using the code from the ghc-mod session letting ghc-mod do the target loading.

### CODE REVIEW

**Comment by edsko** [comment]
Good stuff! Would it make a difference for you if this was on Hackage? If so, when do you think we should release?

**Comment by JPMoresmau** [comment]
It would be good to have it on Hackage, yes, as I think I'm going to push soon a hie plugin that use it, that would simplify the setup for my colleagues there (heads up to @alanz). I have the code currently working so I'm happy to have that version released now!

**Comment by alanz** [comment]
+1

**Comment by edsko** [comment]
Ok, done. Fixed the build on 7.4, and released as 0.2.0.0; http://hackage.haskell.org/package/ghc-dump-tree . Thanks!

**Pull request merged**
