### PR TITLE
Add exception handling to pretty, needed to render full Parsed/Renamed tree.

### PR DESCRIPTION
**Pull request by robinp**
Without the change the MatchGroup in the Parsed/Renamed tree just prints PostTcType (since one of the fields indeed contains the exception, but the main body is interesting nevertheless).

Smoke-tested with the lts-2.22 and lts-5.15 resolvers.

### CODE REVIEW

**Comment by edsko** [comment]
I'm not sure I understand the motivation for this. Could this not be handled in the same way that other exceptions in the tree are handled, in `valueFromData`? Do you have a minimal test case for this that I can try?

**Comment by robinp** [comment]
Not sure what the canonical way is, but you can try any piece of code that
has a function body - the GRHSs will be missing from the Renamed tree
without this patch.

**Comment by robinp** [comment]
Example file content (resolver: lts-2.22):

`main = print 42`

With current head:

```
## Renamed
( HsGroup
    (ValBindsOut
       [ ( NonRecursive
         , Bag.listToBag
             [ L /tmp/Ex.hs:1:1-15
                 (FunBind
                    (L /tmp/Ex.hs:1:1-4
                         { n_loc = /tmp/Ex.hs:1:1-4
                         , n_sort =  { External = Module main Main }
                         , n_uniq = rou
                         , VarName = main
                         })
                    False
                    <<PostTcType>>     <-------------------------- exception
                    WpHole
                    (UFM (fromList []))
                    Nothing)
             ]
         )
       ]
       [])
    []
    []
    []
    []
    []
    []
    []
    []
    []
    []
    []
    []
, [ L /tmp/Ex.hs:1:1
      (ImportDecl
         (L /tmp/Ex.hs:1:1 Prelude)
         Nothing
         False
         False
         False
         True
         Nothing
         Nothing)
  ]
, Just
    [ L <no location info>
        (IEVar
             { n_loc = /tmp/Ex.hs:1:1-4
             , n_sort =  { External = Module main Main }
             , n_uniq = rou
             , VarName = main
             })
    ]
, Nothing
)
```

With patch:

```
## Renamed
( HsGroup
    (ValBindsOut
       [ ( NonRecursive
         , Bag.listToBag
             [ L /tmp/Ex.hs:1:1-15
                 (FunBind
                    (L /tmp/Ex.hs:1:1-4
                         { n_loc = /tmp/Ex.hs:1:1-4
                         , n_sort =  { External = Module main Main }
                         , n_uniq = rou
                         , VarName = main
                         })
                    False
                    (MG        <------------------ we see the function body
                       [ L /tmp/Ex.hs:1:1-15
                           (Match
                              []
                              Nothing
                              (GRHSs
                                 [ L /tmp/Ex.hs:1:8-15
                                     (GRHS
                                        []
                                        (L /tmp/Ex.hs:1:8-15
                                           (HsApp
                                              (L /tmp/Ex.hs:1:8-12
                                                 (HsVar
                                                      { n_loc = <no location info>
                                                      , n_sort =
                                                           { External = Module base System.IO }
                                                      , n_uniq = 0B
                                                      , VarName = print
                                                      }))
                                              (L /tmp/Ex.hs:1:14-15
                                                 (HsOverLit
                                                    (OverLit
                                                       (HsIntegral 42)
                                                       False
                                                       (HsVar
                                                            { n_loc = <no location info>
                                                            , n_sort =
                                                                 { External = Module base GHC.Num }
                                                            , n_uniq = 02A
                                                            , VarName = fromInteger
                                                            })
                                                        { <<PostTcType>> = <<PostTcType>> }))))))
                                 ]
                                 EmptyLocalBinds))
                       ]
                       []
                        { <<PostTcType>> = <<PostTcType>> }   <----- exception here but this is OK
                       FromSource)
                    WpHole
                    (UFM (fromList []))
                    Nothing)
             ]
         )
       ]
       [])
    []
    []
    []
    []
    []
    []
    []
    []
    []
    []
    []
    []
, [ L /tmp/Ex.hs:1:1
      (ImportDecl
         (L /tmp/Ex.hs:1:1 Prelude)
         Nothing
         False
         False
         False
         True
         Nothing
         Nothing)
  ]
, Just
    [ L <no location info>
        (IEVar
             { n_loc = /tmp/Ex.hs:1:1-4
             , n_sort =  { External = Module main Main }
             , n_uniq = rou
             , VarName = main
             })
    ]
, Nothing
)
```

**Comment by edsko** [comment]
Thanks for the example test case and illustrating the difference in test output, very helpful. I've solved in a slightly different way than you proposed as the exception handling infrastructure was intended to make sure that the resulting `Value` was exception free. There was however an exception handler missing in one place; I've added that now. 

Sorry for the slow reply. Ridiculously busy.

**Comment by edsko** [comment]
Released as 0.2.0.2.

**Pull request closed without merging**
